import React from 'react';
import { Transaction, CompanyProfile } from '../types';
import { TrendingUp, TrendingDown, DollarSign, Wallet, Activity, Settings, Mail, Briefcase } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip } from 'recharts';
import { Link } from 'react-router-dom';

interface DashboardProps {
  transactions: Transaction[];
  companyProfile: CompanyProfile;
}

const Dashboard: React.FC<DashboardProps> = ({ transactions, companyProfile }) => {
  // Calculations
  const totalIncome = transactions
    .filter(t => t.type === 'INCOME')
    .reduce((sum, t) => sum + t.amount, 0);

  const totalExpenses = transactions
    .filter(t => t.type === 'EXPENSE')
    .reduce((sum, t) => sum + t.amount, 0);

  const netProfit = totalIncome - totalExpenses;
  const margin = totalIncome > 0 ? (netProfit / totalIncome) * 100 : 0;

  // Prime Cost Calculation (COGS + Labor)
  const primeCost = transactions
    .filter(t => 
      t.type === 'EXPENSE' && 
      (t.category.startsWith('COGS') || t.category.startsWith('Labor'))
    )
    .reduce((sum, t) => sum + t.amount, 0);
  
  const primeCostPct = totalIncome > 0 ? (primeCost / totalIncome) * 100 : 0;

  // Prepare Chart Data (Category breakdown)
  const expenseByCategory = transactions
    .filter(t => t.type === 'EXPENSE')
    .reduce((acc, t) => {
      acc[t.category] = (acc[t.category] || 0) + t.amount;
      return acc;
    }, {} as Record<string, number>);

  const pieData = Object.keys(expenseByCategory).map(key => ({
    name: key,
    value: expenseByCategory[key]
  })).sort((a, b) => b.value - a.value).slice(0, 5); // Top 5

  const COLORS = ['#ef4444', '#f97316', '#eab308', '#84cc16', '#3b82f6'];

  const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    const [year, month, day] = dateStr.split('-');
    return `${day}/${month}/${year}`;
  };

  const generateDailyEmail = () => {
    const today = new Date().toISOString().split('T')[0];
    const dailyTrans = transactions.filter(t => t.date === today);

    if (dailyTrans.length === 0) {
      alert(`No transactions recorded for today (${formatDate(today)}). Add some data first.`);
      return;
    }

    const income = dailyTrans.filter(t => t.type === 'INCOME');
    const expenses = dailyTrans.filter(t => t.type === 'EXPENSE');

    const dayIncome = income.reduce((sum, t) => sum + t.amount, 0);
    const dayExpenses = expenses.reduce((sum, t) => sum + t.amount, 0);
    const dayNet = dayIncome - dayExpenses;

    // Build Email Body
    let body = `Daily Financial Report - ${formatDate(today)}\n`;
    body += `Restaurant: ${companyProfile.name}\n\n`;
    
    body += `SUMMARY\n`;
    body += `----------------------------------------\n`;
    body += `Total Income:    R ${dayIncome.toFixed(2)}\n`;
    body += `Total Expenses:  R ${dayExpenses.toFixed(2)}\n`;
    body += `Net Profit:      R ${dayNet.toFixed(2)}\n`;
    body += `----------------------------------------\n\n`;

    if (income.length > 0) {
      body += `INCOME BREAKDOWN:\n`;
      // Group by payment method or category for summary
      const incomeByMethod = income.reduce((acc, t) => {
         acc[t.paymentMethod] = (acc[t.paymentMethod] || 0) + t.amount;
         return acc;
      }, {} as Record<string, number>);
      
      Object.entries(incomeByMethod).forEach(([method, amt]) => {
         body += `- ${method}: R ${(amt as number).toFixed(2)}\n`;
      });
      body += `\n`;
    }

    if (expenses.length > 0) {
      body += `EXPENSE BREAKDOWN:\n`;
       const expByCat = expenses.reduce((acc, t) => {
         acc[t.category] = (acc[t.category] || 0) + t.amount;
         return acc;
      }, {} as Record<string, number>);

      Object.entries(expByCat).forEach(([cat, amt]) => {
        body += `- ${cat}: R ${(amt as number).toFixed(2)}\n`;
      });
      body += `\n`;
    }

    body += `\nGenerated by BistroBalance`;

    const subject = `Daily Report: ${formatDate(today)} - ${companyProfile.name}`;
    
    // Open Mail Client
    const mailtoLink = `mailto:${companyProfile.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  return (
    <div className="space-y-6">
      <header className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold text-slate-800">Financial Overview</h2>
          <p className="text-slate-500">Real-time snapshot of your restaurant's performance</p>
        </div>
        <div className="flex gap-3">
          <Link 
            to="/loan-account"
            className="inline-flex items-center px-4 py-2 bg-slate-800 text-white border border-transparent rounded-lg text-sm font-medium hover:bg-slate-700 transition-colors shadow-sm"
          >
            <Briefcase className="w-4 h-4 mr-2 text-indigo-300" />
            Loan Account
          </Link>
          <button 
            onClick={generateDailyEmail}
            className="inline-flex items-center px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white border border-transparent rounded-lg text-sm font-medium transition-colors shadow-sm"
          >
            <Mail className="w-4 h-4 mr-2" />
            Email Daily Report
          </button>
          <Link 
            to="/settings"
            className="inline-flex items-center px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50 hover:text-slate-900 transition-colors shadow-sm"
          >
            <Settings className="w-4 h-4 mr-2" />
            Company Config
          </Link>
        </div>
      </header>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <KpiCard 
          title="Total Revenue" 
          value={totalIncome} 
          icon={DollarSign} 
          trend="+12% vs last month" 
          color="emerald" 
        />
        <KpiCard 
          title="Total Expenses" 
          value={totalExpenses} 
          icon={Wallet} 
          trend="-2% vs last month" 
          color="red" 
        />
        <KpiCard 
          title="Net Profit" 
          value={netProfit} 
          icon={TrendingUp} 
          trend={margin.toFixed(1) + "% Margin"} 
          color={netProfit >= 0 ? 'blue' : 'orange'} 
        />
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-slate-500 text-sm font-medium uppercase tracking-wider">Prime Cost</h3>
            <div className={`p-2 rounded-lg bg-purple-100 text-purple-600`}>
              <Activity className="w-5 h-5" />
            </div>
          </div>
          <div className="text-2xl font-bold text-slate-800">{primeCostPct.toFixed(1)}%</div>
          <p className={`text-xs mt-1 ${primeCostPct > 60 ? 'text-red-500' : 'text-emerald-500'}`}>
            {primeCostPct > 60 ? 'Above Target (60%)' : 'Healthy Range'}
          </p>
        </div>
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
        
        {/* Top Expenses */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 h-96">
          <h3 className="text-lg font-semibold text-slate-800 mb-4">Top Expense Categories</h3>
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={pieData}
                cx="50%"
                cy="50%"
                innerRadius={60}
                outerRadius={100}
                paddingAngle={5}
                dataKey="value"
              >
                {pieData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <RechartsTooltip formatter={(value: number) => `R${value.toLocaleString()}`} />
            </PieChart>
          </ResponsiveContainer>
          <div className="flex flex-wrap justify-center gap-2 mt-2">
            {pieData.map((entry, index) => (
              <div key={entry.name} className="flex items-center text-xs text-slate-600">
                <span className="w-2 h-2 rounded-full mr-1" style={{ backgroundColor: COLORS[index % COLORS.length] }}></span>
                {entry.name}
              </div>
            ))}
          </div>
        </div>

        {/* Recent Transactions Mini-Table */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 h-96 overflow-hidden flex flex-col">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-semibold text-slate-800">Recent Transactions</h3>
            <span className="text-xs text-slate-500">Last 5 entries</span>
          </div>
          <div className="overflow-y-auto flex-1 scrollbar-thin">
            <table className="w-full text-sm text-left">
              <thead className="text-xs text-slate-500 uppercase bg-slate-50 sticky top-0">
                <tr>
                  <th className="px-3 py-2">Date</th>
                  <th className="px-3 py-2">Desc</th>
                  <th className="px-3 py-2 text-right">Amount</th>
                </tr>
              </thead>
              <tbody>
                {transactions.slice(0, 8).map((t) => (
                  <tr key={t.id} className="border-b border-slate-100 hover:bg-slate-50">
                    <td className="px-3 py-3 font-medium text-slate-600">{formatDate(t.date)}</td>
                    <td className="px-3 py-3 text-slate-600 truncate max-w-[140px]">{t.description}</td>
                    <td className={`px-3 py-3 text-right font-semibold ${t.type === 'INCOME' ? 'text-emerald-600' : 'text-red-500'}`}>
                      {t.type === 'INCOME' ? '+' : '-'}R{t.amount.toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  );
};

const KpiCard: React.FC<{ title: string; value: number; icon: React.FC<any>; trend: string; color: string }> = ({ title, value, icon: Icon, trend, color }) => {
  const colorClasses = {
    emerald: 'bg-emerald-100 text-emerald-600',
    red: 'bg-red-100 text-red-600',
    blue: 'bg-blue-100 text-blue-600',
    orange: 'bg-orange-100 text-orange-600'
  };

  const selectedColor = colorClasses[color as keyof typeof colorClasses] || colorClasses.blue;

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-slate-500 text-sm font-medium uppercase tracking-wider">{title}</h3>
        <div className={`p-2 rounded-lg ${selectedColor}`}>
          <Icon className="w-5 h-5" />
        </div>
      </div>
      <div className="text-2xl font-bold text-slate-800">
        R{value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
      </div>
      <p className="text-slate-400 text-xs mt-1">{trend}</p>
    </div>
  );
};

export default Dashboard;